# Generated by Django 4.2 on 2023-04-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_info', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vehicle Manufacturer Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Bike Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='bike_info.vehiclemanufacturer')),
            ],
            options={
                'verbose_name': 'Bike Model',
                'verbose_name_plural': 'Bike Models',
            },
        ),
    ]
