# Generated by Django 4.2 on 2023-04-17 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_info', '0004_vehiclemanufacturer_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='bike_info.vehiclecategory'),
            preserve_default=False,
        ),
    ]
