# Generated by Django 4.2 on 2023-04-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_info', '0005_vehiclemodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemanufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Vehicle Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Variant Name')),
                ('slug', models.SlugField(unique=True)),
                ('bike_description', models.TextField(blank=True, null=True, verbose_name='About')),
                ('fuel_economy', models.FloatField(blank=True, null=True, verbose_name='Mileage Km/L')),
                ('fuel_tank_capacity', models.FloatField(blank=True, null=True, verbose_name='Fuel Tank Capacity (in Liters)')),
                ('seat_height', models.IntegerField(blank=True, null=True, verbose_name='Seat Height (in mm)')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='bike_info.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Vehicle Variant',
                'verbose_name_plural': 'Vehicle Variants',
            },
        ),
    ]
