# Generated by Django 4.2 on 2023-04-17 10:00

import devutils.fields
import devutils.middleware
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike_info', '0006_alter_vehiclemanufacturer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Variant Name')),
                ('slug', models.SlugField(unique=True)),
                ('registration_date', models.DateField(verbose_name='Registration date')),
                ('available_after', models.DateField(auto_now_add=True, verbose_name='Availibility Date')),
                ('last_service_date', models.DateField(auto_now_add=True, verbose_name='Last Serviced at')),
                ('day_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rent Per Day')),
                ('created_by', devutils.fields.CurrentUserField(default=devutils.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', devutils.fields.CurrentUserField(default=devutils.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listings', to='bike_info.vehiclevariant')),
            ],
            options={
                'verbose_name': 'Vehicle Listing',
                'verbose_name_plural': 'Vehicle Listings',
            },
        ),
    ]
