# Generated by Django 4.2 on 2023-04-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_info', '0007_vehiclelisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='bike_info.vehiclecategory'),
        ),
    ]
